CREATE TABLE tx_academicjobs_domain_model_job (
	title varchar(255) NOT NULL DEFAULT '',
	employment_start_date date DEFAULT NULL,
	description text,
	image int(11) unsigned NOT NULL DEFAULT '0',
	company_name text NOT NULL DEFAULT '',
	sector text NOT NULL DEFAULT '',
	required_degree text NOT NULL DEFAULT '',
	contractual_relationship text NOT NULL DEFAULT '',
	alumni_recommend tinyint(1) unsigned DEFAULT '0' NOT NULL,
	internationals_welcome tinyint(1) unsigned DEFAULT '0' NOT NULL,
	employment_type int(11) DEFAULT '0' NOT NULL,
	work_location varchar(255) NOT NULL DEFAULT '',
	link varchar(255) NOT NULL DEFAULT '',
	slug varchar(255) NOT NULL DEFAULT '',
	type int(11) DEFAULT '0' NOT NULL,
	contact_name varchar(255) NOT NULL DEFAULT '',
	contact_email varchar(255) NOT NULL DEFAULT '',
	contact_phone varchar(255) NOT NULL DEFAULT '',
	contact_additional_information text,
);
