services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FGTCLB\AcademicJobs\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  FGTCLB\AcademicJobs\EventListener\GenerateJobSlug:
    tags:
      - name: event.listener
        identifier: generateJobSlug
        event: FGTCLB\AcademicJobs\Event\AfterSaveJobEvent

  FGTCLB\AcademicJobs\Registry\AcademicJobsSettingsRegistry:
    public: true
    factory:
      - '@FGTCLB\AcademicJobs\Loader\AcademicJobsSettingsLoader'
      - 'load'
